=== NicolasRodriguezSteuerberg/CosasPc/LMSXI/2evaluacion/XML/exemplo/Esquemas/tiposDatos/Datos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="datos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="texto" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="decimales" type="xs:decimal"/>
        <xs:element name="enteros" type="xs:integer"/>
        <xs:element name="boolean" type="xs:boolean"/>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element name="hora" type="xs:time"/>
        <xs:element name="fechaHora" type="xs:dateTime"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== NicolasRodriguezSteuerberg/CosasPc/1/LMSXI/2evaluacion/XML/exemplo/Esquemas/tiposDatos/Datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<datos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Datos.xsd">
  <texto>Hola muy buenas</texto>
  <decimales>10.3</decimales>
  <enteros>9</enteros>
  <boolean>true</boolean>
  <fecha>2023-02-13</fecha>
  <hora>12:12:43</hora>
  <fechaHora>2023-02-13T12:13:04</fechaHora>
</datos>
