=== NicolasRodriguezSteuerberg/CosasPc/LMSXI/2evaluacion/XML/Repaso/Esquemas/repasoExamen/Repaso.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="emision" type="xs:string"/><!--minOccurs="1" maxOccurs="1"-->
        
        <xs:element name="vendedor">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="cliente">
        <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
          
              <xs:element name="direccion">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="via" type="xs:string"/>
                    <xs:element name="cp" type="xs:integer"/>
                    <xs:element name="localidad" type="xs:string"/>
                    <xs:element name="provincia" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="telefono" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="num" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="articulo" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="denominacion" type="xs:string"/>
              <xs:element name="precio" type="xs:string"/>
              <xs:element name="cantidad" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="iva" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>

          <xs:element name="descuento" minOccurs="0" maxOccurs="1">
            <xs:simpleType>
              <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="100"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        
      </xs:sequence>
      <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== NicolasRodriguezSteuerberg/CosasPc/1/LMSXI/2evaluacion/XML/Repaso/Esquemas/repasoExamen/Repaso.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura id="f-876" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Repaso.xsd">
  <emision>2023-02-28T09:25:02</emision>

  <vendedor id="v-12">
    <nombre>Rodrigo Cuesta Pérez</nombre>    
  </vendedor>
  
  <cliente id="c-9878">
    <nombre>Carmen Rengo Suárez</nombre>
    <direccion>
      <via>Calle Alonso García, 2, 3º A</via>
      <cp>32700</cp>
      <localidad>Vigo</localidad>
      <provincia>Pontevedra</provincia>
    </direccion>
    <telefono num="666111666"/>
    <telefono num="954666111"/>
  </cliente>
  
  <articulo id="a-121" iva="21">
    <denominacion>Silla giratoria modelo C-121</denominacion>
    <precio>98.23</precio>
    <cantidad>1</cantidad>
  </articulo>

  <articulo id="a-9341" iva="21">
    <denominacion>Mesa estudio 120x80 modelo A2-456-X</denominacion>
    <precio>193.23</precio>
    <cantidad>1</cantidad>
  </articulo>

  <articulo id="a-1124" iva="21">
    <denominacion>Lámpara mesa con pantalla naranja modelo AK-987</denominacion>
    <precio>23.12</precio>
    <cantidad>2</cantidad>
  </articulo>

  <descuento>20</descuento>
  
</factura>
