=== NicolasRodriguezSteuerberg/CosasPc/LMSXI/2evaluacion/XML/Boletines/Boletin24/Boletin243.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="listaproductos">
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="articulo" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="codigo" type="xs:string"/>
                    
                    <xs:element name="descripcion">
                      <xs:complexType mixed="true">
                        <xs:attribute name="autor" type="xs:string" use="optional"/>
                      </xs:complexType>
                    <!--OTRA OPCION
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="autor" type="xs:string" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                      -->
                    </xs:element>
                    
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== NicolasRodriguezSteuerberg/CosasPc/1/LMSXI/2evaluacion/XML/Boletines/Boletin24/Boletin243.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaproductos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Boletin243.xsd">
    <articulo>
               <codigo>CD12</codigo>
              <descripcion autor="Juan">Monitor</descripcion>
    </articulo>
    <articulo>
           <codigo>CA12</codigo>
           <descripcion autor="Pepe">Monitor</descripcion>
    </articulo>
    <articulo>
           <codigo>AA99</codigo>
           <descripcion>Teclado</descripcion>
    </articulo>
</listaproductos>
