=== NicolasRodriguezSteuerberg/CosasPc/LMSXI/2evaluacion/XML/Boletines/Boletin26/Boletin26.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!--Ejercicio 1
  <xs:element name="materiales">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="material" type="xs:string"/>
        
        <xs:element name="altura">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:enumeration value="10"/>
              <xs:enumeration value="12"/>
              <xs:enumeration value="14"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="precio" type="xs:decimal"/>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  -->
  
  <!--Ejercicio 2
  <xs:element name="persona">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        
        <xs:element name="altura">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:fractionDigits value="2"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="peso">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:fractionDigits value="3"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  -->
  
  <!--Ejercicio 3-
  <xs:element name="temperaturas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="dia" type="xs:date"/>
        
        <xs:element name="maxima">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="-10"/>
              <xs:maxExclusive value="42"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="minima">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="-10"/>
              <xs:maxExclusive value="42"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  -->
  
  <!--Ejercicio 4-->
  <xs:element name="alumno">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        
        <xs:element name="edad">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="0"/>
              <xs:maxInclusive value="100"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="electrodomestico">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="AEG"/>
              <xs:enumeration value="Sony"/>
              <xs:enumeration value="Balay"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="letra">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[a-z]"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="let">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="x||y||z"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="letras">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[A-Z]{3}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="clave">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[a-z0-9]{6}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="password">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[A-Za-z0-9]{9}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
       <xs:element name="direccion">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="calle" type="xs:string"/>
              <xs:element name="ciudad" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="telefono">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[0-9]{9}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
  
</xs:schema>

=== NicolasRodriguezSteuerberg/CosasPc/1/LMSXI/2evaluacion/XML/Boletines/Boletin26/Boletin26.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Ejercicio 1
<materiales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Boletin26.xsd">
  <material>columna</material>
  <altura>10</altura>
  <precio>12.24</precio>
</materiales>
-->

<!--Ejercicio 2
<persona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Boletin26.xsd">
  <nombre>......... </nombre>
  <altura>23.34 </altura>
  <peso>14.342 </peso>
</persona>
-->

<!--Ejercicio 3
 <temperaturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Boletin26.xsd">
  <dia>2023-03-02</dia>
  <maxima>41</maxima>
  <minima>-10</minima>  
</temperaturas>
-->

<!--Ejercicio 4-->
 <alumno xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Boletin26.xsd">
  <nombre>Juan Garcia</nombre>
  <edad>100</edad>
  <electrodomestico>AEG</electrodomestico>
  <letra>a</letra>
  <let>y</let>
  <letras>ABC</letras>
  <clave>x6e2q5</clave>
  <password>qpegjseit</password>
  <direccion>
    <calle>Avenida de la Fuente</calle>
    <ciudad>Vigo</ciudad>
  </direccion>
  <telefono>987654321</telefono>
</alumno>
